### ISSUE TITLE
not working (as IS)

### ISSUE THREAD

**Issue by ghost** [youknowriad/dropit#1]
Hi, I think there's a problem with GitHub version, wordpress.org is fine but with GitHub version I get a lot of errors. 

I did not install anything else, it's just a simple comparison between 2 versions.

**Comment by ghost** [comment]
I'm basically saying there's a lack of instructions, the title "not working" is probably not accurate

**Comment by youknowriad** [comment]
Thanks for opening the issue, yes it's definitely lacking instructions. But I use the same structure in all my plugins, you can just follow the instructions from GCF https://youknowriad.github.io/gcf/#/contribute

Basically you need to do `npm install && npm run build`. Indeed, It would be good to bring those docs here as well.

**Comment by ghost** [comment]
ok then in #2 you'll find it, I know it's pretty obvious when you read code but trust me, on GitHub, if you have to run some command lines to make the things work it's vital to write them in your readme.md
