### ISSUE TITLE
add giphy support

### ISSUE THREAD

**Issue by ghost** [youknowriad/dropit#4]
As you suggested on Twitter that would be cool to have 1 plugin for several services such as unsplash && giphy see https://github.com/TweetPressFr/wp-giphy-oembed. I've basically copied your code to make my own embed. 
However I don't know if we are allowed to upload gif to the media library. Giphy has a branding policy.

**Comment by youknowriad** [comment]
I added you as a collaborator :). I'm fine with external links like you did if it's not possible to upload as well.

What is the branding policy of Giphy?

I added you as a collaborator, feel free to open a PR on a branch or something.

**Comment by ghost** [comment]
Thanks,

basically they provide a limited key for dev purpose and if you want to "scale" (quota can be reached fast in fact) you have to submit a request (I've already done it). 

Regarding the branding policy https://developers.giphy.com/docs/#access

**Comment by ghost** [comment]
https://giphy.com/terms see 4.
not very clear to me

**Comment by ghost** [comment]
see #5
