### ISSUE TITLE
Enhancement: easy insertion as featured images

### ISSUE THREAD

**Issue by dartiss** [youknowriad/dropit#6]
Unless I've missed something, there isn't an easy way to use an unsplash/giphy image as the featured image. It would be nice to be able to add this feature - maybe another icon on the image results that lets you add it as the featured image (after uploading).

**Comment by youknowriad** [comment]
👍 Nice idea, I'll try it when I have some time unless someone else beat me to it :)

**Comment by ghost** [comment]
that would be cool for any core/image block in fact @dartiss @youknowriad.

**Comment by dartiss** [comment]
I would agree but the merged ticket #7 is for Unsplash only - what about Giphy support for featured images?
